server:
  port: 12345

config:
  secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/backend
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update # production -> validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  docker:
    compose:
      file: ./docker/docker-compose.yml
      lifecycle-management: start_only

